name: Run golangci-lint on backend fiber

on:
  push:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.golangci.yml'
      - '.golangci.yaml'
      - '.github/workflows/lint.yml'

  pull_request:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.golangci.yml'
      - '.golangci.yaml'
      - '.github/workflows/lint.yml'

permissions:
  contents: read

jobs:
  golangci-backend:
    name: Run golangci-lint on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
          check-latest: true
          cache: true

      - name: Install Golangci-Lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.8

      - name: Run Golangci
        run: golangci-lint run ./... --fix --timeout 5m0s
